name: Deploy bezzabot
on:
  push:
    paths-ignore:
      - 'README.md'
      - '.git/**'

env:
  CARGO_TERM_COLOR: always

jobs:
  linux_arm6:
    name: "Bezzabot build for Raspberry Pi 2 ARMv6"
    runs-on: radiopapus/bezzabot
    strategy:
      fail-fast: false
      matrix:
        target:
          - arm-unknown-linux-gnueabihf
    steps:
      - uses: actions/checkout@v4
      - name: Build project
        run: cargo build --release --target=${{matrix.target}}
      - uses: actions/cache@v3
        continue-on-error: false
        with:
          key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}
          restore-keys: ${{ runner.os }}-cargo-
          path: |
              ~/.cargo/bin/
              ~/.cargo/registry/index/
              ~/.cargo/registry/cache/
              ~/.cargo/git/db/
              target/
      - name: List target
        run: find ./target
      - name: Compress
        run: |
          mkdir -p ./artifacts
          NAME="bezzabot"
          mv ./target/$RUST_TARGET/release/$NAME ./$NAME
          tar -czf ./artifacts/$NAME-$RUST_TARGET.tar.gz $NAME
      - name: Archive artifact
        uses: actions/upload-artifact@v3
        with:
          name: archive
          path: |
            ./artifacts
