name: Deploy bezzabot
on:
  push:
    paths-ignore:
      - 'README.md'
      - '.git/**'
env:
  CROSS_CONTAINER_IN_CONTAINER: true
jobs:
  linux_arm6:
    name: Linux ARMv6
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          target: arm-unknown-linux-musleabihf
          override: true
      - uses: actions-rs/cargo@v1
        with:
          use-cross: true
          command: build
          args: --release --target arm-unknown-linux-musleabihf HOSTNAME=$(docker ps -ql)
      - name: List target
        run: find ./target
      - name: Compress
        run: |
          mkdir -p ./artifacts
          EXEC=$NAME
          if [[ $GITHUB_REF_TYPE =~ ^tag$ ]]; then
            TAG=$GITHUB_REF_NAME
          else
            TAG=$GITHUB_SHA
          fi
          mv ./target/$TARGET/release/$EXEC ./$EXEC
          tar -czf ./artifacts/$NAME-$TARGET-$TAG.tar.gz $EXEC
      - name: Archive artifact
        uses: actions/upload-artifact@v3
        with:
          name: result
          path: |
            ./artifacts
