name: Deploy bezzabot
on:
  push:
    paths-ignore:
      - 'README.md'
      - '.git/**'

env:
  CARGO_TERM_COLOR: always

jobs:
  linux_arm6:
    name: "Bezzabot build for Raspberry Pi 2 ARMv6"
    runs-on: ubuntu-latest
    container:
      image: ghcr.io/radiopapus/bezzabot
      volumes:
        - .:/bezzabot
      credentials:
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}
    strategy:
      fail-fast: false
      matrix:
        target:
          - arm-unknown-linux-gnueabihf
    steps:
      - uses: actions/checkout@v4
      - uses: actions/cache@v3
        continue-on-error: false
        with:
          key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}
          path: |
            ~/.cargo/bin/
            ~/.cargo/registry/index/
            ~/.cargo/registry/cache/
            ~/.cargo/git/db/
            target/
      - name: Build project
        run: cargo build --release --target=${{matrix.target}}
      - name: Compress
        run: |
          mkdir -p ./artifacts
          NAME="bezzabot"
          mv ./target/$RUST_TARGET/release/$NAME ./$NAME
          tar -czf ./artifacts/$NAME-$RUST_TARGET.tar.gz $NAME
      - name: Archive artifact
        uses: actions/upload-artifact@v3
        with:
          name: archive
          path: ./artifacts
